### ISSUE TITLE
Telemetry Statement

### ISSUE THREAD

**Issue by nomandera** [ProtonMail/proton-mail-export#10]
[v1.0.4](https://github.com/ProtonMail/proton-mail-export/releases/tag/v1.0.4) included `Added generic telemetry.`

but I can find no generic Telemetry policy or summary of usage etc.

Please could you consider adding something that sets out your approach to Telemetry so that it is open and there is no possibility of anyone incorrectly "reading between the lines".

**Comment by gabor-meszaros** [comment]
Hi @nomandera, Thanks for the question. You can find our approach to data collection in our Privacy Policy: https://proton.me/legal/privacy#2-data-collection-and-usage
We will add this link to our release notes as well.

**Comment by nomandera** [comment]
Perfect thank you.
